version: '3.8'
services:
  nginx-static-home-page:
    image: nginx:latest
    container_name: nginx_static_home_page
    ports:
      - "8081:80"
    volumes:
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf
      - /staticfiles:/var/www/static
    restart: unless-stopped
